---
kind: pipeline
type: docker
name: default

clone:
  depth: 1

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

steps:
- name: Build
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build .

- name: Publish core package
  image: plugins/npm
  when:
    event:
    - tag
  settings:
    username:
      from_secret: npm_username
    password:
      from_secret: npm_password
    email:
      from_secret: npm_email
    folder: core

- name: Publish angular package
  image: plugins/npm
  when:
    event:
    - tag
  settings:
    username:
      from_secret: npm_username
    password:
      from_secret: npm_password
    email:
      from_secret: npm_email
    folder: angular/dist

- name: Publish react package
  image: plugins/npm
  when:
    event:
    - tag
  settings:
    username:
      from_secret: npm_username
    password:
      from_secret: npm_password
    email:
      from_secret: npm_email
    folder: react

- name: Generate docs
  image: harbor.zyra.ca/public/zmdocs:v1.1.0
  when:
    branch:
    - master
  commands:
  - zmdocs g

- name: Publish docs
  image: plugins/gh-pages
  when:
    event:
      exclude:
      - pull_request
    branch:
    - master
  settings:
    username:
      from_secret: gh_user
    password:
      from_secret: gh_token
    pages_directory: docs

#- name: Update example project
#  image: plugins/downstream
#  settings:
#    server: https://drone.zyra.ca
#    token:
#      from_secret: drone_token
#    repositories:
#    - zyra/ionic-super-tabs-example
#    fork: true

---
kind: signature
hmac: f293244b93f5c4503d73898116e17fb369d97c8ebb4eb14de5402d80ee794e66

...
