---
kind: pipeline
type: docker
name: default

clone:
  depth: 1

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

steps:
- name: Fast build
  image: docker
  when:
    event:
      exclude:
      - tag
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build .

- name: Build
  image: node:12
  when:
    event:
    - tag
  commands:
  - npm i
  - ./super-tabs.sh setup
  - ./super-tabs.sh build

- name: Publish
  image: node:12
  when:
    event:
    - tag
  environment:
    NPM_TOKEN:
      from_secret: npm_token
  commands:
    - echo '//registry.npmjs.org/:_authToken=$${NPM_TOKEN}' > ~/.npmrc
    - ./super-tabs.sh publish

- name: Generate docs
  image: harbor.zyra.ca/public/zmdocs:v1.1.0
  when:
    branch:
    - master
  commands:
  - zmdocs g

- name: Publish docs
  image: plugins/gh-pages
  when:
    event:
      exclude:
      - pull_request
    branch:
    - master
  settings:
    username:
      from_secret: gh_user
    password:
      from_secret: gh_token
    pages_directory: docs

#- name: Update example project
#  image: plugins/downstream
#  settings:
#    server: https://drone.zyra.ca
#    token:
#      from_secret: drone_token
#    repositories:
#    - zyra/ionic-super-tabs-example
#    fork: true

---
kind: signature
hmac: 325be6f79fe9c33c34d9376df0ffce76ae06e1e831666c434bdfa2c45837b85b

...
